1) Check inotify-tools is installed. 2) Run the command before waiting for changes

diff --git a/run-when-files-change b/run-when-files-change
--- a/run-when-files-change
+++ b/run-when-files-change
@@ -4,6 +4,13 @@
 # https://intoli.com/blog/running-selenium-with-headless-firefox/
 # export MOZ_HEADLESS='1'
 
+if [ ! `command -v inotifywait` ]; then
+    echo "ERROR: 'inotify-tools' is not installed!"
+    exit 1
+fi
+
+$@
+
 while true; do
     OUTPUT=$(inotifywait --quiet --recursive --event modify --exclude '\.swp' .)
     clear
